name: README build

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 */1 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 1. checkout
        uses: actions/checkout@v1
      - name: 2. setup node
        uses: actions/setup-node@v1
        with:
          node-version: '13.x'
      - name: 3. install dependencies
        run: npm install
      - name: 4. generate README file
        run: node index.js
      - name: 5. push new README.md
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}